---
title: 10 Lessons in Humility
author: Bizovi Mihai
date: '2023-04-10'
categories: ["philosophy"]
---

I was trying to articulate a philosophy for the courses I teach and accidentally wrote 10 non-exhaustive principles for life, which are also lessons in humility. It will not be surprising if the humble wonder practice by John Vervaeke shaped these ideas.

- There is no shortcut to **deep understanding**
    - Of a domain, especially in an **interdisciplinary** setting
    - With communities engaged in an evolving **dialogue**
- There is no shortcut to being **skillful** at something
- The journey from novice to expert is **not linear**, however, the "interest compounds"
- The journey need not be painful, but it can be **seriously playful**, a source of wonder and meaning
- Without **skin in the game**, we can't claim we truly get something
- Without a **vision** which is flexible enough, but at the same time long-lived:
    - In the case of **rigidity** - there is a risk of being stuck, pursue obsessively, counterproductively the wrong thing
    - In the case of **everything goes** - there is a risk of wandering aimlessly and not finding a home
- Fixating on beliefs and **propositional knowing** (the facts!) is counterproductive. Which should put into question all written above
- Fixating on *skills* makes you lose the grasp of the **big picture**


## John Vervaeke's Humble Wonder

Practicing the Socratic learned ignorance about the self:

- There is so much I do not know about myself because of all of the [combinatorially explosive] facts.
- There is so much I shall never know about myself because of all of the fate.
- There is so much I refuse to see about myself because of all of my foolishness.
- There is so much I am unable to see about myself because of all of my faults.

Practicing the Learned Ignorance about the world:

- There is so much I do not know about the world because of all of the facts.
- There is so much I shall never know about the world because of all of the fate.
- There is so much I refuse to see about the world because of all of my foolishness.
- There is so much I am unable to see about the world because of all of my faults.


