project:
  type: website

website:
  title: "{Art, Math, Philosophy}"
  site-url: https://blog.economic-cybernetics.com
  description: "{Art, Math, Philosophy}"
  favicon: img/icon.png
  open-graph:
    locale: es_ES
    site-name: "{Art, Math, Philosophy}"
  google-analytics: "UA-104200881-1"

  navbar:
    right:
      - href: about.qmd
        text: "About Me"
      - icon: bi-journal-bookmark
        href: https://course.economic-cybernetics.com/
        text: "Decision-Making"
      - icon: github
        href: https://github.com/bizovi/decision-making
      - icon: linkedin
        href: https://www.linkedin.com/in/bizovi-mihai-56982abb/
      - icon: rss
        href: index.xml
format:
  html:
    theme: journal
    css: styles.css



